import Header from '@/components/header/page'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
       <Footer />
        </body>
    </html>
  )
}
